---

- hosts: all
  become: true
  pre_tasks:

  - name install updates (Ubuntu)
  apt:
    upgrade: dist
    upgrade_cahce: yes

- host: Vm_servers
  become: true
  tasks:
  - name: install apache2 pnd php package
    package:
      name:
        - apache2 
        - libapache2-mod-php 
      state: latest
    when: ansible_distribution == "Ubuntu" 

- host: Azure_servers
  become: true
  tasks:
  - name: install mariadb package
    package:
      name:
        -  mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
