---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    
    tags: Ubuntu,apache2,db
    
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    
- hosts: Vm_servers
  become: true
  tasks:
  - name: install apache2 and php package
    
    tags: Ubuntu,apache2,vm-local,vm
    
    package:
      name:
        - apache2 
        - libapache2-mod-php 
      state: latest
    when: ansible_distribution == "Ubuntu" 

- hosts: Azure_servers
  become: true
  tasks:
  - name: install apache2 an php package

    tags: Ubuntu,apache2,vm-azure,vm
    
    package:
      name:
        - apache2 
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
