---

- hosts: all
  become: true
  pre_tasks:

  - name: update cache (Ubuntu)
    
    tags: Ubuntu,apache2,db
    
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base


- hosts: Vm_servers
  become: true
  roles:
    - Vm_servers


- hosts: WinSrv_Vm
  become: true
  become_method: runas
  become_user: administrator
  roles:
    - WinSrv_Vm
