- name: install apache2 and php package
  tags: Ubuntu,apache2,vm-local,vm
       
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}" 
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: change KeepAliveTimeout 5 -> 10
  tags: apache, apache2, Ubuntu, vm-local, vm

  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin someone@somewhere.net
  when: ansible_distribution == "Ubuntu"
  notify: restart_apache

- name: start and enable apache service (Ubuntu)
  tags: apache, apache2, Ubuntu, vm-local, vm

  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: upload default test page
  tags: Ubuntu,apache2,vm-azure,vm
    
  copy: 
    src: /var/www/html/index.html 
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 644

- name: install zippackage (7zip)
  tags: Ubuntu, file-servwers, 7zip

  package:
    name:
      - "{{ zip_package }}"
    state: latest
  when:  ansible_facts.eth0.ipv4.address == "192.168.98.3"

